language: node_js
node_js:
    - "7"
    - "6"
    - "5"
    - "4"
    - "0.12"
    - "0.10"

cache:
  directories:
    - node_modules
    - ~/.npm

script:
  - npm test

after_success:
  - npm install coveralls@^2.11
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true