language: node_js
sudo: false

node_js:
  - 8
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm prune

after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
