language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"
    - "6"
    - "7"

cache:
  directories:
    - node_modules
    - ~/.npm

script:
  - npm test && nyc report --reporter=text-lcov | coveralls

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true