language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.nvm

script:
  - npm test
  - npm prune

after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

notifications:
  on_success: change
  on_failure: always
