cache:
  - node_modules
environment:
  matrix:
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
test_script:
  - npm test